kind: pipeline
type: docker
name: atlas

steps:
  - name: docker_atlas_raw_release
    image: plugins/ecr
    settings:
      dockerfile: Dockerfile
      registry:
        from_secret: org_ecr_registry
      repo: atlas
      tags: ${DRONE_TAG}-atlas-raw
      region: eu-west-1
    when:
      event: tag

  - name: docker_atlas_embedded_hbase_solr_release
    image: plugins/ecr
    settings:
      build_args:
        - PROFILE=-Pdist,embedded-hbase-solr
      dockerfile: Dockerfile
      registry:
        from_secret: org_ecr_registry
      region: eu-west-1
      repo: atlas
      tags: ${DRONE_TAG}-atlas-embedded-hbase-solr
    when:
      event: tag