services:
  atlas:
    build:
      context: .
      dockerfile: Dockerfile.atlas
      args:
        - ATLAS_BACKEND=${ATLAS_BACKEND}
        - ATLAS_SERVER_JAVA_VERSION=${ATLAS_SERVER_JAVA_VERSION}
        - ATLAS_VERSION=${ATLAS_VERSION}
    image: atlas:latest
    container_name: atlas
    hostname: atlas.example.com
    stdin_open: true
    tty: true
    networks:
      - atlas
    volumes:
      - ./data:/home/atlas/data
      - ./config/atlas/${ATLAS_BACKEND}/${ATLAS_INDEX_BACKEND}/atlas-application.properties:/opt/atlas/conf/atlas-application.properties:ro
      - ./config/atlas/users-credentials.properties:/opt/atlas/conf/users-credentials.properties:ro
    ports:
      - "21000:21000"
    depends_on:
      atlas-backend:
        condition: service_healthy
      atlas-kafka:
        condition: service_started
      atlas-index:
        condition: service_healthy
      atlas-zk:
        condition: service_started
    environment:
      - ATLAS_BACKEND
      - ATLAS_INDEX_BACKEND
      - ATLAS_SERVER_JAVA_VERSION
      - ATLAS_VERSION
    command:
      - /home/atlas/scripts/atlas.sh

  atlas-backend:
    extends:
      service: ${ATLAS_BACKEND}
      file: docker-compose.atlas-backend.yml

  atlas-index:
    extends:
      service: ${ATLAS_INDEX_BACKEND}
      file: docker-compose.atlas-index.yml

  atlas-opensearch-dashboards:
    extends:
      file: docker-compose.atlas-common.yml
      service: atlas-opensearch-dashboards
    profiles:
      - opensearch-index
    depends_on:
      atlas-index:
        condition: service_healthy
    environment:
      - OPENSEARCH_HOSTS=["http://atlas-index:9200"]

  atlas-kafka:
    extends:
      service: atlas-kafka
      file: docker-compose.atlas-common.yml

  atlas-zk:
    extends:
      service: atlas-zk
      file: docker-compose.atlas-common.yml

networks:
  atlas:
    name: atlasnw
