# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

FROM opensearchproject/opensearch:3.7.0

ENV discovery.type=single-node \
    DISABLE_INSTALL_DEMO_CONFIG=true \
    DISABLE_SECURITY_PLUGIN=true \
    OPENSEARCH_JAVA_OPTS="-Xms512m -Xmx512m"

EXPOSE 9200 9600

HEALTHCHECK --interval=10s --timeout=10s --retries=12 \
  CMD curl -sf "http://localhost:9200/_cluster/health?wait_for_status=yellow&timeout=5s" || exit 1
