# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

FROM atlas-base:latest

ARG ATLAS_VERSION

COPY ./scripts/atlas.sh                              ${ATLAS_SCRIPTS}/
COPY ./dist/apache-atlas-${ATLAS_VERSION}-bin.tar.gz /tmp/

RUN tar xfz /tmp/apache-atlas-${ATLAS_VERSION}-bin.tar.gz --directory=/opt/ && \
    ln -s /opt/apache-atlas-${ATLAS_VERSION} ${ATLAS_HOME} && \
    rm -f /tmp/apache-atlas-${ATLAS_VERSION}-bin.tar.gz && \
    mkdir -p /var/run/atlas && \
    mkdir -p /var/log/atlas && \
    mkdir -p /home/atlas/data && \
    rm -rf ${ATLAS_HOME}/logs && \
    ln -s /var/log/atlas ${ATLAS_HOME}/logs && \
    ln -s /home/atlas/data ${ATLAS_HOME}/data && \
    chown -R atlas:atlas ${ATLAS_HOME}/ /var/run/atlas/ /var/log/atlas/

VOLUME /home/atlas/data

ENTRYPOINT [ "/home/atlas/scripts/atlas.sh" ]
