services:
  atlas-hive:
    build:
      context: .
      dockerfile: Dockerfile.atlas-hive
      args:
        - HIVE_HADOOP_VERSION=${HIVE_HADOOP_VERSION}
        - HIVE_VERSION=${HIVE_VERSION}
        - ATLAS_VERSION=${ATLAS_VERSION}
    image: atlas-hive
    container_name: atlas-hive
    hostname: atlas-hive.example.com
    stdin_open: true
    tty: true
    networks:
      - atlas
    healthcheck:
      test: [ "CMD-SHELL", "su hdfs -c \"/opt/hadoop/bin/hdfs dfsadmin -report | grep -q 'Live datanodes'\"" ]
      interval: 30s
      timeout: 10s
      retries: 30
      start_period: 40s
    ports:
      - "10000:10000"
    depends_on:
      atlas-db:
        condition: service_healthy
      atlas-hadoop:
        condition: service_healthy
      atlas-zk:
        condition: service_started
      atlas-kafka:
        condition: service_started
    environment:
      - HIVE_HADOOP_VERSION
      - HIVE_VERSION
      - ATLAS_VERSION

  atlas-db:
    extends:
      service: atlas-db
      file: docker-compose.atlas-common.yml

  atlas-zk:
    extends:
      service: atlas-zk
      file: docker-compose.atlas-common.yml

  atlas-kafka:
    extends:
      service: atlas-kafka
      file: docker-compose.atlas-common.yml

networks:
  atlas:
    name: atlasnw
