version: '3'
services:
  atlas:
    build:
      context: .
      dockerfile: Dockerfile.atlas
      args:
        - ATLAS_VERSION=${ATLAS_VERSION}
    image: atlas:latest
    container_name: atlas
    hostname: atlas.example.com
    stdin_open: true
    tty: true
    networks:
      - atlas
    volumes:
      - ./data:/home/atlas/data
    ports:
      - "21000:21000"
    depends_on:
      - atlas-base
    environment:
      - ATLAS_VERSION
    command:
      - /home/atlas/scripts/atlas.sh

networks:
  atlas:
