# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

FROM atlas-base:latest

ARG ATLAS_BACKEND
ARG ATLAS_SERVER_JAVA_VERSION
ARG ATLAS_VERSION
ARG TARGETARCH
# Matches postgresql.version in the root pom; used only when ATLAS_BACKEND=postgres.
ARG POSTGRESQL_JDBC_VERSION=42.7.7

ENV JAVA_HOME=/usr/lib/jvm/java-${ATLAS_SERVER_JAVA_VERSION}-openjdk-${TARGETARCH}
RUN update-java-alternatives --set /usr/lib/jvm/java-1.${ATLAS_SERVER_JAVA_VERSION}.0-openjdk-${TARGETARCH}

COPY ./scripts/atlas.sh                                 ${ATLAS_SCRIPTS}/
COPY ./dist/apache-atlas-${ATLAS_VERSION}-server.tar.gz /home/atlas/dist/

RUN tar xfz /home/atlas/dist/apache-atlas-${ATLAS_VERSION}-server.tar.gz --directory=/opt/ && \
    ln -s /opt/apache-atlas-${ATLAS_VERSION} ${ATLAS_HOME} && \
    rm -f /home/atlas/dist/apache-atlas-${ATLAS_VERSION}-server.tar.gz && \
    mkdir -p /var/run/atlas /var/log/atlas /home/atlas/data ${ATLAS_HOME}/hbase/conf ${ATLAS_HOME}/libext && \
    rm -rf ${ATLAS_HOME}/logs && \
    ln -s /var/log/atlas ${ATLAS_HOME}/logs && \
    ln -s /home/atlas/data ${ATLAS_HOME}/data && \
    mkdir -p ${ATLAS_HOME}/server/webapp/atlas && \
    cd ${ATLAS_HOME}/server/webapp/atlas && \
    jar -xf ../atlas.war && \
    rm -f ../atlas.war && \
    if [ "${ATLAS_BACKEND}" = "postgres" ]; then \
      curl -fsSL -o ${ATLAS_HOME}/libext/postgresql-${POSTGRESQL_JDBC_VERSION}.jar \
        https://repo1.maven.org/maven2/org/postgresql/postgresql/${POSTGRESQL_JDBC_VERSION}/postgresql-${POSTGRESQL_JDBC_VERSION}.jar; \
    fi && \
    chown -R atlas:atlas ${ATLAS_HOME}/ /var/run/atlas/ /var/log/atlas/

COPY ./scripts/hbase-site.xml ${ATLAS_HOME}/hbase/conf/

VOLUME /home/atlas/data

EXPOSE 21000

ENTRYPOINT [ "/home/atlas/scripts/atlas.sh" ]
