services:
  atlas-solr:
    build:
      context: .
      dockerfile: Dockerfile.atlas-solr
    image: atlas-solr
    container_name: atlas-solr
    hostname: atlas-solr.example.com
    networks:
      - atlas
    ports:
      - "8983:8983"

  atlas-kafka:
    build:
      context: .
      dockerfile: Dockerfile.atlas-kafka
      args:
        - KAFKA_VERSION=${KAFKA_VERSION}
        - ATLAS_VERSION=${ATLAS_VERSION}
    image: atlas-kafka
    container_name: atlas-kafka
    hostname: atlas-kafka.example.com
    stdin_open: true
    tty: true
    networks:
      - atlas
    ports:
      - "9092:9092"
    depends_on:
      atlas-zk:
        condition: service_started
    environment:
      - KAFKA_VERSION
      - ATLAS_VERSION

  atlas-zk:
    build:
      context: .
      dockerfile: Dockerfile.atlas-zk
    image: atlas-zk
    container_name: atlas-zk
    hostname: atlas-zk.example.com
    networks:
      - atlas
    ports:
      - "2181:2181"

  atlas-db:
    image: postgres:13.21
    container_name: atlas-db
    hostname: atlas-db.example.com
    networks:
      - atlas
    environment:
      POSTGRES_HOST: atlas-db
      POSTGRES_PORT: 5432
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: atlasR0cks!
      HIVE_DB_PASSWORD: atlasR0cks!
      ATLAS_DB_PASSWORD: atlasR0cks!
      ATLAS_SCHEMA_FILE: /tmp/create_schema.sql
    volumes:
      - ./config/init_postgres.sh:/tmp/init_postgres.sh:ro
      - ../../graphdb/janusgraph-rdbms/src/main/resources/META-INF/postgres/create_schema.sql:/tmp/create_schema.sql:ro
    command:
      - /tmp/init_postgres.sh
    healthcheck:
      test: 'su -c "pg_isready -q" postgres'
      interval: 30s
      timeout: 10s
      retries: 30
      start_period: 40s
