"""Cleanup module for removing test-harness artifacts from previous runs.

Discovers entities, glossaries, and typedefs created by the test harness
using predictable naming patterns, then deletes them in dependency order.

Naming patterns:
  - Entities: qualifiedName starts with "test-harness-"
  - TypeDefs: name matches *_{10-digit-timestamp}_{hex} (e.g. Th_1710000000_a1b2c3)
  - Glossaries: name contains a 10-digit timestamp segment
"""

import re
import sys
import time
from collections import defaultdict

# Regex for typedef names generated by unique_type_name(): PREFIX_TIMESTAMP_HEX
_TYPEDEF_PATTERN = re.compile(r"_\d{10}_[0-9a-f]{4,8}$")

# Regex for glossary/entity names generated by unique_name(): prefix-TIMESTAMP-HEX
_NAME_PATTERN = re.compile(r"-\d{10}-[0-9a-f]{4,8}$")

# Entity QN prefix
_ENTITY_QN_PREFIX = "test-harness-"


def _search_entities(client, query, size=100, max_pages=50):
    """Paginate an index search query, return list of {guid, typeName, qualifiedName}."""
    results = []
    for page in range(max_pages):
        dsl = dict(query)
        dsl["from"] = page * size
        dsl["size"] = size
        resp = client.post("/search/indexsearch", json_data={"dsl": dsl})
        if resp.status_code != 200:
            print(f"  [cleanup] Search returned {resp.status_code}, stopping pagination")
            break
        body = resp.json()
        entities = body.get("searchResults", body.get("entities", []))
        if not entities:
            break
        for e in entities:
            attrs = e.get("attributes", {})
            results.append({
                "guid": e.get("guid"),
                "typeName": e.get("typeName"),
                "qualifiedName": attrs.get("qualifiedName", ""),
                "name": attrs.get("name", ""),
            })
        if len(entities) < size:
            break
    return results


def _find_test_entities(client):
    """Find all entities with QN starting with 'test-harness-'.

    Searches both ACTIVE and DELETED entities so we catch soft-deleted
    leftovers that still block typedef deletion via ES references.
    """
    all_results = []
    for state in ("ACTIVE", "DELETED"):
        query = {
            "query": {
                "bool": {
                    "must": [
                        {"wildcard": {"qualifiedName": f"{_ENTITY_QN_PREFIX}*"}},
                        {"term": {"__state": state}},
                    ]
                }
            },
            "sort": [{"qualifiedName": {"order": "asc"}}],
        }
        results = _search_entities(client, query)
        if results:
            print(f"  [cleanup] Found {len(results)} {state} test entities")
        all_results.extend(results)

    # Deduplicate by GUID (entity might appear in both states during transition)
    seen = set()
    deduped = []
    for e in all_results:
        guid = e.get("guid")
        if guid and guid not in seen:
            seen.add(guid)
            deduped.append(e)
    return deduped


def _find_test_glossaries(client):
    """Find glossaries/terms/categories matching test-harness name patterns."""
    results = []
    for type_name in ["AtlasGlossary", "AtlasGlossaryTerm", "AtlasGlossaryCategory"]:
        query = {
            "query": {
                "bool": {
                    "must": [
                        {"term": {"__typeName.keyword": type_name}},
                    ]
                }
            },
            "sort": [{"__timestamp": {"order": "asc"}}],
        }
        entities = _search_entities(client, query, size=100, max_pages=10)
        for e in entities:
            name = e.get("name", "")
            qn = e.get("qualifiedName", "")
            # Match test-harness naming patterns
            if _NAME_PATTERN.search(name) or qn.startswith(_ENTITY_QN_PREFIX):
                results.append(e)
    return results


def _find_test_typedefs(client):
    """Find typedefs matching the test-harness naming pattern."""
    resp = client.get("/types/typedefs/headers")
    if resp.status_code != 200:
        print(f"  [cleanup] GET /types/typedefs/headers returned {resp.status_code}")
        return []

    body = resp.json()
    results = []

    # typedefs/headers returns a flat list of {name, guid, category, ...}
    # or may be nested under category keys
    if isinstance(body, list):
        for td in body:
            name = td.get("name", "")
            if _TYPEDEF_PATTERN.search(name):
                results.append(td)
    elif isinstance(body, dict):
        for category_key in ("classificationDefs", "structDefs", "entityDefs",
                             "enumDefs", "businessMetadataDefs", "relationshipDefs"):
            for td in body.get(category_key, []):
                name = td.get("name", "")
                if _TYPEDEF_PATTERN.search(name):
                    td["_category"] = category_key
                    results.append(td)
    return results


def _print_all_artifacts(entities, glossaries, typedefs):
    """Print every artifact that will be deleted, grouped by category."""
    print("\n=== Test Harness Cleanup ===\n")

    total = len(entities) + len(glossaries) + len(typedefs)
    if total == 0:
        print("Nothing to clean up.")
        return 0

    # --- Entities ---
    if entities:
        by_type = defaultdict(list)
        for e in entities:
            by_type[e.get("typeName", "Unknown")].append(e)

        print(f"Entities ({len(entities)}):")
        for tn in sorted(by_type.keys()):
            items = by_type[tn]
            print(f"  {tn} ({len(items)}):")
            for e in items:
                qn = e.get("qualifiedName", "?")
                guid = e.get("guid", "?")
                print(f"    - {qn[:100]}  ({guid})")

    # --- Glossaries ---
    if glossaries:
        g_by_type = defaultdict(list)
        for g in glossaries:
            g_by_type[g.get("typeName", "Unknown")].append(g)

        print(f"\nGlossary objects ({len(glossaries)}):")
        for tn in sorted(g_by_type.keys()):
            items = g_by_type[tn]
            print(f"  {tn} ({len(items)}):")
            for g in items:
                name = g.get("name", "?")
                guid = g.get("guid", "?")
                print(f"    - {name[:80]}  ({guid})")

    # --- TypeDefs ---
    if typedefs:
        td_by_cat = defaultdict(list)
        for td in typedefs:
            cat = td.get("_category") or td.get("category", "unknown")
            td_by_cat[cat].append(td)

        print(f"\nTypeDefs ({len(typedefs)}):")
        for cat in sorted(td_by_cat.keys()):
            items = td_by_cat[cat]
            print(f"  {cat} ({len(items)}):")
            for td in items:
                name = td.get("name", "?")
                print(f"    - {name}")

    print(f"\nTotal: {total} artifacts")
    return total


def _delete_entities(client, entities, verbose=False):
    """Hard-delete (purge) entities in dependency-safe order.

    Uses DELETE /entity/guid/{guid}?deleteType=PURGE for all entities.
    The AuditFilter reads the ``deleteType`` query parameter and sets
    ``RequestContext.setPurgeRequested(true)`` which triggers HardDeleteHandlerV1.
    Hard delete fully removes entities from graph + ES, which is required
    before typedef deletion can succeed (classificationHasReferences checks ES).

    Glossary entities use their specific REST endpoints for proper cascade handling.
    """
    errors = []

    # Sort: categories first, then terms, then glossaries, then processes, then rest
    priority = {
        "AtlasGlossaryCategory": 0,
        "AtlasGlossaryTerm": 1,
        "AtlasGlossary": 2,
        "Process": 3,
    }
    sorted_entities = sorted(entities, key=lambda e: priority.get(e.get("typeName", ""), 10))

    deleted = 0
    failed = 0
    total = len(sorted_entities)

    for e in sorted_entities:
        guid = e.get("guid")
        tn = e.get("typeName", "?")
        qn = e.get("qualifiedName", "?")
        if not guid:
            continue

        # Glossary entities use specific endpoints for proper cascade handling
        if tn == "AtlasGlossary":
            resp = client.delete(f"/glossary/{guid}", params={"deleteType": "PURGE"}, timeout=60)
        elif tn == "AtlasGlossaryTerm":
            resp = client.delete(f"/glossary/term/{guid}", params={"deleteType": "PURGE"}, timeout=60)
        elif tn == "AtlasGlossaryCategory":
            resp = client.delete(f"/glossary/category/{guid}", params={"deleteType": "PURGE"}, timeout=60)
        else:
            # Hard delete (purge) via entity endpoint
            resp = client.delete(
                f"/entity/guid/{guid}",
                params={"deleteType": "PURGE"},
                timeout=60,
            )

        if resp.status_code in (200, 204, 404):
            deleted += 1
            if verbose:
                print(f"  [{deleted + failed}/{total}] Purged {tn} {qn[:80]}")
        else:
            failed += 1
            errors.append(f"{tn} {guid}: HTTP {resp.status_code}")
            if verbose:
                print(f"  [{deleted + failed}/{total}] FAILED {tn} {qn[:80]} -> {resp.status_code}")

    print(f"  Hard-deleted {deleted}/{total} entities"
          + (f" ({failed} failed)" if failed else ""))
    return errors


def _delete_typedefs(client, typedefs, verbose=False):
    """Delete typedefs by name.

    Uses retries=0 and timeout=60 because typedef DELETE returning 500
    means the server rejected it (e.g. type has references in ES) —
    retrying the same request won't help, it just wastes minutes.
    """
    errors = []
    for i, td in enumerate(typedefs, 1):
        name = td.get("name")
        if not name:
            continue
        resp = client.delete(f"/types/typedef/name/{name}", timeout=120, retries=0)
        if resp.status_code in (200, 204):
            if verbose:
                print(f"  [{i}/{len(typedefs)}] Deleted typedef {name}")
        else:
            errors.append(f"typedef {name}: HTTP {resp.status_code}")
            if verbose:
                print(f"  [{i}/{len(typedefs)}] FAILED typedef {name} -> {resp.status_code}")
    return errors


def run_cleanup_all(client, verbose=False):
    """Discover and delete all test-harness artifacts.

    Lists every artifact, asks for confirmation, then deletes all or aborts.
    """
    print("Scanning for test-harness artifacts...")

    entities = _find_test_entities(client)
    glossaries = _find_test_glossaries(client)
    typedefs = _find_test_typedefs(client)

    total = _print_all_artifacts(entities, glossaries, typedefs)

    if total == 0:
        return

    # Confirmation prompt — all or nothing
    try:
        answer = input("\nDelete ALL listed artifacts? [y/N]: ").strip().lower()
    except (EOFError, KeyboardInterrupt):
        print("\nAborted.")
        return

    if answer not in ("y", "yes"):
        print("Aborted. Nothing deleted.")
        return

    print(f"\nDeleting {total} artifacts...")

    all_errors = []

    # 1. Delete glossary objects first (categories, terms, glossaries)
    if glossaries:
        print(f"\n  Deleting {len(glossaries)} glossary objects...")
        errs = _delete_entities(client, glossaries, verbose=verbose)
        all_errors.extend(errs)

    # 2. Delete entities (processes first, then datasets, etc.)
    if entities:
        print(f"\n  Deleting {len(entities)} entities...")
        errs = _delete_entities(client, entities, verbose=verbose)
        all_errors.extend(errs)

    # 3. Wait for ES to settle before typedef deletion
    #    classificationHasReferences() checks ES for __traitNames references;
    #    hard-deleted entities need time to disappear from ES indices.
    has_entities = bool(entities) or bool(glossaries)
    if has_entities and typedefs:
        es_settle = 30
        print(f"\n  Waiting {es_settle}s for ES to reflect entity deletions "
              f"before typedef cleanup...")
        time.sleep(es_settle)

    # 4. Delete typedefs last
    if typedefs:
        print(f"\n  Deleting {len(typedefs)} typedefs...")
        errs = _delete_typedefs(client, typedefs, verbose=verbose)
        all_errors.extend(errs)

    # Summary
    print(f"\n=== Cleanup complete ===")
    print(f"  Deleted: {total - len(all_errors)}")
    if all_errors:
        print(f"  Errors:  {len(all_errors)}")
        for err in all_errors:
            print(f"    - {err}")
