"""Domain/Product QualifiedName move/reparent tests.

Tests domain promotion (sub -> super), demotion (super -> sub),
cross-domain moves, product moves between domains, cycle prevention,
and multi-level cascade verification.  Verifies that the server-side
preprocessor cascades QN changes to all children.

Server-side QN patterns (DataDomainPreProcessor.java):
  SuperDomain: default/domain/{nanoId}/super
  SubDomain:   {parentDomainQN}/domain/{nanoId}
  Product:     {parentDomainQN}/product/{nanoId}

Key behaviors:
  - Promote (sub->super): nanoId preserved
  - Demote (super->sub): nanoId MAY be regenerated by the server
  - Cross-domain move (sub->sub): nanoId typically preserved via getOwnQualifiedNameForChild()
  - Child cascade: nanoIds preserved (last 2 path segments extracted)
"""

import re
import time

from core.decorators import suite, test
from core.assertions import (
    assert_status, assert_status_in, assert_field_equals,
    assert_field_not_empty, SkipTestError,
)
from core.data_factory import (
    build_domain_entity, build_data_product_entity, unique_name,
)


# ---- QN helpers ----

# SuperDomain: default/domain/{nanoId}/super
_SUPER_DOMAIN_RE = re.compile(r"^default/domain/([^/]+)/super$")
# SubDomain: .../domain/{nanoId}  (parent prefix varies)
_SUB_DOMAIN_RE = re.compile(r"^(.+)/domain/([^/]+)$")
# Product: .../product/{nanoId}
_PRODUCT_RE = re.compile(r"^(.+)/product/([^/]+)$")


def _extract_super_nano(qn):
    """Extract nanoId from a super-domain QN, or None."""
    m = _SUPER_DOMAIN_RE.match(qn)
    return m.group(1) if m else None


def _extract_sub_nano(qn):
    """Return (parent_prefix, nanoId) from a sub-domain QN, or (None, None)."""
    m = _SUB_DOMAIN_RE.match(qn)
    return (m.group(1), m.group(2)) if m else (None, None)


def _extract_product_nano(qn):
    """Return (parent_prefix, nanoId) from a product QN, or (None, None)."""
    m = _PRODUCT_RE.match(qn)
    return (m.group(1), m.group(2)) if m else (None, None)


def _read_entity_qn(client, guid):
    """GET entity by GUID and return its qualifiedName (or None)."""
    resp = client.get(f"/entity/guid/{guid}")
    if resp.status_code != 200:
        return None
    return resp.json().get("entity", {}).get("attributes", {}).get("qualifiedName")


def _read_entity_attrs(client, guid):
    """GET entity by GUID and return its attributes dict (or {})."""
    resp = client.get(f"/entity/guid/{guid}")
    if resp.status_code != 200:
        return {}
    return resp.json().get("entity", {}).get("attributes", {})


def _wait_for_qn_change(client, guid, old_qn, max_wait=30, interval=3):
    """Poll until entity QN differs from old_qn, or timeout. Returns final QN."""
    deadline = time.time() + max_wait
    qn = old_qn
    while time.time() < deadline:
        qn = _read_entity_qn(client, guid)
        if qn and qn != old_qn:
            return qn
        time.sleep(interval)
    return qn


def _create_entity(client, entity_payload, label="entity"):
    """POST /entity and return (guid, resp) or raise SkipTestError."""
    for attempt in range(3):
        resp = client.post("/entity", json_data={"entity": entity_payload}, timeout=60)
        if resp.status_code != 408 or attempt == 2:
            break
        time.sleep(5 * (attempt + 1))

    if resp.status_code in (400, 403):
        raise SkipTestError(
            f"{label} creation returned {resp.status_code} — "
            f"Keycloak/preprocessor not configured on this environment"
        )
    assert_status(resp, 200)

    body = resp.json()
    creates = body.get("mutatedEntities", {}).get("CREATE", [])
    updates = body.get("mutatedEntities", {}).get("UPDATE", [])
    entities = creates or updates
    assert entities, f"{label} creation returned no entities in mutatedEntities"
    return entities[0]["guid"], resp


@suite("domain_qn_moves", depends_on_suites=["entity_crud"],
       description="Domain/Product QualifiedName move and cascade tests")
class DomainQnMovesSuite:

    def setup(self, client, ctx):
        self.domain_a_name = unique_name("move-domA")
        self.domain_b_name = unique_name("move-domB")
        self.sub_name = unique_name("move-sub")
        self.subsub_name = unique_name("move-subsub")
        self.prod_sub_name = unique_name("move-prod-sub")
        self.prod_a_name = unique_name("move-prod-a")
        # Extended test entities
        self.domain_c_name = unique_name("move-domC")
        self.sub2_name = unique_name("move-sub2")
        self.prod_sub2_name = unique_name("move-prod-sub2")
        self.prod_a2_name = unique_name("move-prod-a2")

    # ================================================================
    # CREATE hierarchy under domain A
    # ================================================================

    @test("create_super_domain_a", tags=["move", "data_mesh", "crud"], order=1)
    def test_create_super_domain_a(self, client, ctx):
        """Create super domain A.  Verify QN: default/domain/{nanoId}/super."""
        entity = build_domain_entity(name=self.domain_a_name)
        guid, _ = _create_entity(client, entity, "DomainA")
        ctx.register_entity("move_domain_a", guid, "DataDomain")
        ctx.register_entity_cleanup(guid)

        qn = _read_entity_qn(client, guid)
        assert qn, f"Expected qualifiedName on domain A ({guid})"
        ctx.set("move_domain_a_qn", qn)

        nano = _extract_super_nano(qn)
        assert nano, (
            f"Domain A QN does not match super-domain pattern "
            f"'default/domain/{{nanoId}}/super', got: {qn}"
        )
        ctx.set("move_domain_a_nano", nano)
        print(f"  [domain-move] Domain A: guid={guid}, qn={qn}")

    @test("create_super_domain_b", tags=["move", "data_mesh", "crud"], order=2)
    def test_create_super_domain_b(self, client, ctx):
        """Create super domain B.  Verify QN: default/domain/{nanoId}/super."""
        entity = build_domain_entity(name=self.domain_b_name)
        guid, _ = _create_entity(client, entity, "DomainB")
        ctx.register_entity("move_domain_b", guid, "DataDomain")
        ctx.register_entity_cleanup(guid)

        qn = _read_entity_qn(client, guid)
        assert qn, f"Expected qualifiedName on domain B ({guid})"
        ctx.set("move_domain_b_qn", qn)

        nano = _extract_super_nano(qn)
        assert nano, (
            f"Domain B QN does not match super-domain pattern, got: {qn}"
        )
        ctx.set("move_domain_b_nano", nano)
        print(f"  [domain-move] Domain B: guid={guid}, qn={qn}")

    @test("create_sub_domain", tags=["move", "data_mesh", "crud"], order=3,
          depends_on=["create_super_domain_a"])
    def test_create_sub_domain(self, client, ctx):
        """Create subdomain under A.  Verify QN: {domainA_qn}/domain/{nanoId}."""
        parent_guid = ctx.get_entity_guid("move_domain_a")
        entity = build_domain_entity(name=self.sub_name, parent_domain_guid=parent_guid)
        guid, _ = _create_entity(client, entity, "SubDomain")
        ctx.register_entity("move_sub", guid, "DataDomain")
        ctx.register_entity_cleanup(guid)

        qn = _read_entity_qn(client, guid)
        assert qn, f"Expected qualifiedName on subdomain ({guid})"
        ctx.set("move_sub_qn", qn)

        parent_prefix, nano = _extract_sub_nano(qn)
        domain_a_qn = ctx.get("move_domain_a_qn")
        assert parent_prefix == domain_a_qn, (
            f"Subdomain parent prefix mismatch: expected {domain_a_qn}, "
            f"got {parent_prefix} (full QN: {qn})"
        )
        ctx.set("move_sub_nano", nano)
        print(f"  [domain-move] Sub: guid={guid}, qn={qn}")

    @test("create_sub_sub_domain", tags=["move", "data_mesh", "crud"], order=4,
          depends_on=["create_sub_domain"])
    def test_create_sub_sub_domain(self, client, ctx):
        """Create sub-sub-domain under subdomain.  Verify QN: {sub_qn}/domain/{nanoId}."""
        parent_guid = ctx.get_entity_guid("move_sub")
        entity = build_domain_entity(name=self.subsub_name, parent_domain_guid=parent_guid)
        guid, _ = _create_entity(client, entity, "SubSubDomain")
        ctx.register_entity("move_subsub", guid, "DataDomain")
        ctx.register_entity_cleanup(guid)

        qn = _read_entity_qn(client, guid)
        assert qn, f"Expected qualifiedName on sub-sub-domain ({guid})"
        ctx.set("move_subsub_qn", qn)

        parent_prefix, nano = _extract_sub_nano(qn)
        sub_qn = ctx.get("move_sub_qn")
        assert parent_prefix == sub_qn, (
            f"Sub-sub parent prefix mismatch: expected {sub_qn}, "
            f"got {parent_prefix} (full QN: {qn})"
        )
        ctx.set("move_subsub_nano", nano)
        print(f"  [domain-move] SubSub: guid={guid}, qn={qn}")

    @test("create_product_under_sub", tags=["move", "data_mesh", "crud"], order=5,
          depends_on=["create_sub_domain"])
    def test_create_product_under_sub(self, client, ctx):
        """Create product under subdomain.  Verify QN: {sub_qn}/product/{nanoId}."""
        domain_guid = ctx.get_entity_guid("move_sub")
        entity = build_data_product_entity(name=self.prod_sub_name, domain_guid=domain_guid)
        guid, _ = _create_entity(client, entity, "ProductUnderSub")
        ctx.register_entity("move_prod_sub", guid, "DataProduct")
        ctx.register_entity_cleanup(guid)

        qn = _read_entity_qn(client, guid)
        assert qn, f"Expected qualifiedName on product ({guid})"
        ctx.set("move_prod_sub_qn", qn)

        parent_prefix, nano = _extract_product_nano(qn)
        sub_qn = ctx.get("move_sub_qn")
        assert parent_prefix == sub_qn, (
            f"Product parent prefix mismatch: expected {sub_qn}, "
            f"got {parent_prefix} (full QN: {qn})"
        )
        ctx.set("move_prod_sub_nano", nano)
        print(f"  [domain-move] ProdSub: guid={guid}, qn={qn}")

    @test("create_product_under_a", tags=["move", "data_mesh", "crud"], order=6,
          depends_on=["create_super_domain_a"])
    def test_create_product_under_a(self, client, ctx):
        """Create product under domain A."""
        domain_guid = ctx.get_entity_guid("move_domain_a")
        entity = build_data_product_entity(name=self.prod_a_name, domain_guid=domain_guid)
        guid, _ = _create_entity(client, entity, "ProductUnderA")
        ctx.register_entity("move_prod_a", guid, "DataProduct")
        ctx.register_entity_cleanup(guid)

        qn = _read_entity_qn(client, guid)
        assert qn, f"Expected qualifiedName on product ({guid})"
        ctx.set("move_prod_a_qn", qn)

        parent_prefix, nano = _extract_product_nano(qn)
        domain_a_qn = ctx.get("move_domain_a_qn")
        assert parent_prefix == domain_a_qn, (
            f"Product parent prefix mismatch: expected {domain_a_qn}, "
            f"got {parent_prefix} (full QN: {qn})"
        )
        ctx.set("move_prod_a_nano", nano)
        print(f"  [domain-move] ProdA: guid={guid}, qn={qn}")

    # ================================================================
    # CREATE (extended): Domain C, Sub2 under A, products
    # ================================================================

    @test("create_super_domain_c", tags=["move", "data_mesh", "crud"], order=7)
    def test_create_super_domain_c(self, client, ctx):
        """Create super domain C for cross-domain move tests."""
        entity = build_domain_entity(name=self.domain_c_name)
        guid, _ = _create_entity(client, entity, "DomainC")
        ctx.register_entity("move_domain_c", guid, "DataDomain")
        ctx.register_entity_cleanup(guid)

        qn = _read_entity_qn(client, guid)
        assert qn, f"Expected qualifiedName on domain C ({guid})"
        ctx.set("move_domain_c_qn", qn)

        nano = _extract_super_nano(qn)
        assert nano, (
            f"Domain C QN does not match super-domain pattern, got: {qn}"
        )
        ctx.set("move_domain_c_nano", nano)
        print(f"  [domain-move] Domain C: guid={guid}, qn={qn}")

    @test("create_second_sub_under_a", tags=["move", "data_mesh", "crud"], order=8,
          depends_on=["create_super_domain_a"])
    def test_create_second_sub_under_a(self, client, ctx):
        """Create second subdomain under A for cross-domain move + cascade test."""
        parent_guid = ctx.get_entity_guid("move_domain_a")
        entity = build_domain_entity(name=self.sub2_name, parent_domain_guid=parent_guid)
        guid, _ = _create_entity(client, entity, "Sub2UnderA")
        ctx.register_entity("move_sub2", guid, "DataDomain")
        ctx.register_entity_cleanup(guid)

        qn = _read_entity_qn(client, guid)
        assert qn, f"Expected qualifiedName on sub2 ({guid})"
        ctx.set("move_sub2_qn", qn)

        parent_prefix, nano = _extract_sub_nano(qn)
        domain_a_qn = ctx.get("move_domain_a_qn")
        assert parent_prefix == domain_a_qn, (
            f"Sub2 parent prefix mismatch: expected {domain_a_qn}, "
            f"got {parent_prefix} (full QN: {qn})"
        )
        ctx.set("move_sub2_nano", nano)
        print(f"  [domain-move] Sub2: guid={guid}, qn={qn}")

    @test("create_prod_under_sub2", tags=["move", "data_mesh", "crud"], order=9,
          depends_on=["create_second_sub_under_a"])
    def test_create_prod_under_sub2(self, client, ctx):
        """Create product under Sub2 to verify cascade when Sub2 moves."""
        domain_guid = ctx.get_entity_guid("move_sub2")
        entity = build_data_product_entity(name=self.prod_sub2_name,
                                           domain_guid=domain_guid)
        guid, _ = _create_entity(client, entity, "ProductUnderSub2")
        ctx.register_entity("move_prod_sub2", guid, "DataProduct")
        ctx.register_entity_cleanup(guid)

        qn = _read_entity_qn(client, guid)
        assert qn, f"Expected qualifiedName on prod-sub2 ({guid})"
        ctx.set("move_prod_sub2_qn", qn)

        parent_prefix, nano = _extract_product_nano(qn)
        sub2_qn = ctx.get("move_sub2_qn")
        assert parent_prefix == sub2_qn, (
            f"ProdSub2 parent prefix mismatch: expected {sub2_qn}, "
            f"got {parent_prefix} (full QN: {qn})"
        )
        ctx.set("move_prod_sub2_nano", nano)
        print(f"  [domain-move] ProdSub2: guid={guid}, qn={qn}")

    # ================================================================
    # MOVE 1: Promote subdomain to superdomain (remove parentDomain)
    # ================================================================

    @test("move_sub_to_super", tags=["move", "data_mesh"], order=10,
          depends_on=["create_sub_domain", "create_sub_sub_domain",
                       "create_product_under_sub"])
    def test_move_sub_to_super(self, client, ctx):
        """MOVE: Remove parentDomain to promote subdomain to superdomain."""
        guid = ctx.get_entity_guid("move_sub")
        current_qn = ctx.get("move_sub_qn")
        assert guid and current_qn, "Subdomain not created"

        resp = client.post("/entity", json_data={
            "entity": {
                "typeName": "DataDomain",
                "guid": guid,
                "attributes": {
                    "qualifiedName": current_qn,
                    "name": self.sub_name,
                },
                "relationshipAttributes": {
                    "parentDomain": None,
                },
            }
        }, timeout=60)
        assert_status_in(resp, [200, 400, 403])
        if resp.status_code != 200:
            raise SkipTestError(
                f"Promote subdomain returned {resp.status_code} — "
                f"move operation may not be supported"
            )
        print(f"  [domain-move] Promote sub->super: {resp.status_code}")

    @test("verify_sub_became_super", tags=["move", "data_mesh"], order=11,
          depends_on=["move_sub_to_super"])
    def test_verify_sub_became_super(self, client, ctx):
        """Verify promoted subdomain has super-domain QN pattern (with polling)."""
        guid = ctx.get_entity_guid("move_sub")
        old_nano = ctx.get("move_sub_nano")
        old_qn = ctx.get("move_sub_qn")

        # Poll for QN change
        new_qn = _wait_for_qn_change(client, guid, old_qn, max_wait=30)
        assert new_qn and new_qn != old_qn, (
            f"QN did not change after promote: still {new_qn}"
        )

        # Should now match default/domain/{nanoId}/super
        nano = _extract_super_nano(new_qn)
        assert nano, (
            f"Promoted domain QN does not match super-domain pattern, got: {new_qn}"
        )
        assert nano == old_nano, (
            f"NanoId changed during promote: expected {old_nano}, got {nano}"
        )

        # parentDomainQualifiedName should be null/empty
        attrs = _read_entity_attrs(client, guid)
        parent_qn = attrs.get("parentDomainQualifiedName")
        assert not parent_qn, (
            f"Expected null parentDomainQualifiedName after promote, got: {parent_qn}"
        )

        ctx.set("move_sub_qn", new_qn)
        print(f"  [domain-move] Verified promote: new QN={new_qn}")

    @test("verify_cascade_after_promote", tags=["move", "data_mesh"], order=12,
          depends_on=["verify_sub_became_super"])
    def test_verify_cascade_after_promote(self, client, ctx):
        """Verify sub-sub-domain and product QNs updated with new prefix."""
        new_sub_qn = ctx.get("move_sub_qn")  # now a super-domain QN
        old_subsub_nano = ctx.get("move_subsub_nano")
        old_prod_nano = ctx.get("move_prod_sub_nano")
        old_subsub_qn = ctx.get("move_subsub_qn")
        old_prod_qn = ctx.get("move_prod_sub_qn")

        # Check sub-sub-domain (poll for cascade)
        subsub_guid = ctx.get_entity_guid("move_subsub")
        subsub_qn = _wait_for_qn_change(client, subsub_guid, old_subsub_qn, max_wait=30)
        assert subsub_qn, f"Expected qualifiedName on sub-sub after cascade ({subsub_guid})"
        parent_prefix, nano = _extract_sub_nano(subsub_qn)
        assert parent_prefix == new_sub_qn, (
            f"Sub-sub parent prefix not cascaded: expected {new_sub_qn}, "
            f"got {parent_prefix} (full QN: {subsub_qn})"
        )
        assert nano == old_subsub_nano, (
            f"Sub-sub nanoId changed during cascade: expected {old_subsub_nano}, got {nano}"
        )
        ctx.set("move_subsub_qn", subsub_qn)
        print(f"  [domain-move] Sub-sub after promote: {subsub_qn}")

        # Check product under subdomain (poll for cascade)
        prod_guid = ctx.get_entity_guid("move_prod_sub")
        prod_qn = _wait_for_qn_change(client, prod_guid, old_prod_qn, max_wait=30)
        assert prod_qn, f"Expected qualifiedName on product after cascade ({prod_guid})"
        prod_prefix, prod_nano = _extract_product_nano(prod_qn)
        assert prod_prefix == new_sub_qn, (
            f"Product parent prefix not cascaded: expected {new_sub_qn}, "
            f"got {prod_prefix} (full QN: {prod_qn})"
        )
        assert prod_nano == old_prod_nano, (
            f"Product nanoId changed during cascade: expected {old_prod_nano}, got {prod_nano}"
        )
        ctx.set("move_prod_sub_qn", prod_qn)
        print(f"  [domain-move] Product after promote: {prod_qn}")

    # ================================================================
    # MOVE 2: Demote superdomain to subdomain of B
    # ================================================================

    @test("move_super_to_sub_of_b", tags=["move", "data_mesh"], order=20,
          depends_on=["verify_cascade_after_promote"])
    def test_move_super_to_sub_of_b(self, client, ctx):
        """MOVE: Add parentDomain pointing to domain B to demote to subdomain."""
        guid = ctx.get_entity_guid("move_sub")
        current_qn = ctx.get("move_sub_qn")
        domain_b_guid = ctx.get_entity_guid("move_domain_b")
        assert guid and current_qn and domain_b_guid, "Required entities not created"

        resp = client.post("/entity", json_data={
            "entity": {
                "typeName": "DataDomain",
                "guid": guid,
                "attributes": {
                    "qualifiedName": current_qn,
                    "name": self.sub_name,
                },
                "relationshipAttributes": {
                    "parentDomain": {
                        "guid": domain_b_guid,
                        "typeName": "DataDomain",
                    },
                },
            }
        }, timeout=60)
        assert_status_in(resp, [200, 400, 403])
        if resp.status_code != 200:
            raise SkipTestError(
                f"Demote to sub-of-B returned {resp.status_code} — "
                f"move operation may not be supported"
            )
        print(f"  [domain-move] Demote super->sub-of-B: {resp.status_code}")

    @test("verify_became_sub_of_b", tags=["move", "data_mesh"], order=21,
          depends_on=["move_super_to_sub_of_b"])
    def test_verify_became_sub_of_b(self, client, ctx):
        """Verify QN changed to {domainB_qn}/domain/{nanoId}.

        NOTE: On super->sub demotion, the server MAY regenerate the nanoId.
        We only assert the parent prefix is correct.
        """
        guid = ctx.get_entity_guid("move_sub")
        old_qn = ctx.get("move_sub_qn")
        domain_b_qn = ctx.get("move_domain_b_qn")

        # Poll for QN change
        new_qn = _wait_for_qn_change(client, guid, old_qn, max_wait=30)
        assert new_qn and new_qn != old_qn, (
            f"QN did not change after demotion: still {new_qn}"
        )

        parent_prefix, nano = _extract_sub_nano(new_qn)
        assert parent_prefix == domain_b_qn, (
            f"Moved domain parent prefix mismatch: expected {domain_b_qn}, "
            f"got {parent_prefix} (full QN: {new_qn})"
        )

        # Store the (possibly new) nanoId for cascade checks
        ctx.set("move_sub_nano", nano)
        ctx.set("move_sub_qn", new_qn)

        attrs = _read_entity_attrs(client, guid)
        parent_domain_qn = attrs.get("parentDomainQualifiedName")
        assert parent_domain_qn == domain_b_qn, (
            f"parentDomainQualifiedName mismatch: expected {domain_b_qn}, "
            f"got {parent_domain_qn}"
        )
        print(f"  [domain-move] Verified move to B: new QN={new_qn}")

    @test("verify_cascade_after_move_to_b", tags=["move", "data_mesh"], order=22,
          depends_on=["verify_became_sub_of_b"])
    def test_verify_cascade_after_move_to_b(self, client, ctx):
        """Verify all children QNs cascade-updated to domainB prefix."""
        new_sub_qn = ctx.get("move_sub_qn")
        old_subsub_qn = ctx.get("move_subsub_qn")
        old_prod_qn = ctx.get("move_prod_sub_qn")

        # Check sub-sub-domain (poll for cascade)
        subsub_guid = ctx.get_entity_guid("move_subsub")
        subsub_qn = _wait_for_qn_change(client, subsub_guid, old_subsub_qn, max_wait=30)
        assert subsub_qn, f"Expected qualifiedName on sub-sub after cascade ({subsub_guid})"
        parent_prefix, nano = _extract_sub_nano(subsub_qn)
        assert parent_prefix == new_sub_qn, (
            f"Sub-sub parent prefix not cascaded to B: expected {new_sub_qn}, "
            f"got {parent_prefix} (full QN: {subsub_qn})"
        )
        # Child nanoId should be preserved during cascade
        ctx.set("move_subsub_nano", nano)
        ctx.set("move_subsub_qn", subsub_qn)
        print(f"  [domain-move] Sub-sub after move to B: {subsub_qn}")

        # Check product (poll for cascade)
        prod_guid = ctx.get_entity_guid("move_prod_sub")
        prod_qn = _wait_for_qn_change(client, prod_guid, old_prod_qn, max_wait=30)
        assert prod_qn, f"Expected qualifiedName on product after cascade ({prod_guid})"
        prod_prefix, prod_nano = _extract_product_nano(prod_qn)
        assert prod_prefix == new_sub_qn, (
            f"Product parent prefix not cascaded to B: expected {new_sub_qn}, "
            f"got {prod_prefix} (full QN: {prod_qn})"
        )
        ctx.set("move_prod_sub_nano", prod_nano)
        ctx.set("move_prod_sub_qn", prod_qn)
        print(f"  [domain-move] Product after move to B: {prod_qn}")

    # ================================================================
    # MOVE 3: Move product to domain A
    # ================================================================

    @test("move_product_to_domain_a", tags=["move", "data_mesh"], order=30,
          depends_on=["create_product_under_sub", "create_super_domain_a",
                       "verify_cascade_after_move_to_b"])
    def test_move_product_to_domain_a(self, client, ctx):
        """MOVE: Change dataDomain to domain A.  Verify product QN prefix."""
        import json

        prod_guid = ctx.get_entity_guid("move_prod_sub")
        current_qn = ctx.get("move_prod_sub_qn")
        domain_a_guid = ctx.get_entity_guid("move_domain_a")
        domain_a_qn = ctx.get("move_domain_a_qn")
        assert prod_guid and current_qn and domain_a_guid, "Required entities not created"

        # dataProductAssetsDSL is mandatory for product updates
        assets_dsl = json.dumps({
            "query": {"bool": {"must": [
                {"term": {"__guid": "00000000-0000-0000-0000-000000000000"}},
            ]}}
        })

        resp = client.post("/entity", json_data={
            "entity": {
                "typeName": "DataProduct",
                "guid": prod_guid,
                "attributes": {
                    "qualifiedName": current_qn,
                    "name": self.prod_sub_name,
                    "dataProductAssetsDSL": assets_dsl,
                },
                "relationshipAttributes": {
                    "dataDomain": {
                        "guid": domain_a_guid,
                        "typeName": "DataDomain",
                    },
                },
            }
        }, timeout=60)
        assert_status_in(resp, [200, 400, 403])
        if resp.status_code != 200:
            raise SkipTestError(
                f"Move product to A returned {resp.status_code} — "
                f"move operation may not be supported"
            )

        # Poll for QN change
        new_qn = _wait_for_qn_change(client, prod_guid, current_qn, max_wait=30)
        assert new_qn, f"Expected qualifiedName on product after move ({prod_guid})"

        prod_prefix, prod_nano = _extract_product_nano(new_qn)
        assert prod_prefix == domain_a_qn, (
            f"Product parent prefix after move mismatch: expected {domain_a_qn}, "
            f"got {prod_prefix} (full QN: {new_qn})"
        )
        ctx.set("move_prod_sub_nano", prod_nano)
        ctx.set("move_prod_sub_qn", new_qn)
        print(f"  [domain-move] Product after move to A: {new_qn}")

    # ================================================================
    # MOVE 4: Cycle prevention — moving parent under own child
    # ================================================================

    @test("try_cycle_parent_to_child", tags=["move", "data_mesh", "validation"],
          order=33, depends_on=["create_second_sub_under_a", "move_product_to_domain_a"])
    def test_try_cycle_parent_to_child(self, client, ctx):
        """VALIDATE: Moving A under Sub2 should be rejected (circular reference).

        Sub2 is a child of A. Moving A under Sub2 would create:
        Sub2 -> A -> Sub2 (cycle). The preprocessor should detect this
        and return 400 with a circular reference error.
        """
        a_guid = ctx.get_entity_guid("move_domain_a")
        a_qn = ctx.get("move_domain_a_qn")
        sub2_guid = ctx.get_entity_guid("move_sub2")
        assert a_guid and a_qn and sub2_guid, "Required entities not created"

        resp = client.post("/entity", json_data={
            "entity": {
                "typeName": "DataDomain",
                "guid": a_guid,
                "attributes": {
                    "qualifiedName": a_qn,
                    "name": self.domain_a_name,
                },
                "relationshipAttributes": {
                    "parentDomain": {
                        "guid": sub2_guid,
                        "typeName": "DataDomain",
                    },
                },
            }
        }, timeout=60)
        # Should be rejected — either 400 (circular reference) or 409 (conflict)
        assert resp.status_code in (400, 409), (
            f"Expected 400/409 for circular move attempt, got {resp.status_code}. "
            f"Server should prevent moving a parent domain under its own child."
        )
        print(f"  [domain-move] Cycle prevention: {resp.status_code} (expected rejection)")

    @test("verify_a_unchanged_after_cycle_reject", tags=["move", "data_mesh", "validation"],
          order=34, depends_on=["try_cycle_parent_to_child"])
    def test_verify_a_unchanged_after_cycle_reject(self, client, ctx):
        """Verify domain A QN is unchanged after rejected circular move."""
        a_guid = ctx.get_entity_guid("move_domain_a")
        expected_qn = ctx.get("move_domain_a_qn")

        attrs = _read_entity_attrs(client, a_guid)
        actual_qn = attrs.get("qualifiedName")
        assert actual_qn == expected_qn, (
            f"Domain A QN changed after rejected move: expected {expected_qn}, "
            f"got {actual_qn}"
        )

        # Should still be a super domain (no parent)
        parent_qn = attrs.get("parentDomainQualifiedName")
        assert not parent_qn, (
            f"Domain A got a parentDomainQualifiedName after rejected move: {parent_qn}"
        )
        print(f"  [domain-move] Domain A unchanged after cycle reject: {actual_qn}")

    # ================================================================
    # MOVE 5: Cross-domain subdomain move (Sub2: A -> C) with cascade
    # ================================================================

    @test("move_sub2_to_c", tags=["move", "data_mesh", "cross_domain"], order=35,
          depends_on=["verify_a_unchanged_after_cycle_reject", "create_super_domain_c",
                       "create_prod_under_sub2"])
    def test_move_sub2_to_c(self, client, ctx):
        """MOVE: Move Sub2 from under A to under C.

        Tests cross-domain subdomain move.  ProdSub2 should cascade.
        """
        sub2_guid = ctx.get_entity_guid("move_sub2")
        sub2_qn = ctx.get("move_sub2_qn")
        domain_c_guid = ctx.get_entity_guid("move_domain_c")
        assert sub2_guid and sub2_qn and domain_c_guid, "Required entities not created"

        resp = client.post("/entity", json_data={
            "entity": {
                "typeName": "DataDomain",
                "guid": sub2_guid,
                "attributes": {
                    "qualifiedName": sub2_qn,
                    "name": self.sub2_name,
                },
                "relationshipAttributes": {
                    "parentDomain": {
                        "guid": domain_c_guid,
                        "typeName": "DataDomain",
                    },
                },
            }
        }, timeout=60)
        assert_status_in(resp, [200, 400, 403])
        if resp.status_code != 200:
            raise SkipTestError(
                f"Move Sub2 to C returned {resp.status_code}"
            )
        print(f"  [domain-move] Move Sub2 from A to C: {resp.status_code}")

    @test("verify_sub2_under_c", tags=["move", "data_mesh", "cross_domain"], order=36,
          depends_on=["move_sub2_to_c"])
    def test_verify_sub2_under_c(self, client, ctx):
        """Verify Sub2 QN now has domain C as parent prefix."""
        sub2_guid = ctx.get_entity_guid("move_sub2")
        old_qn = ctx.get("move_sub2_qn")
        domain_c_qn = ctx.get("move_domain_c_qn")

        new_qn = _wait_for_qn_change(client, sub2_guid, old_qn, max_wait=30)
        assert new_qn and new_qn != old_qn, (
            f"Sub2 QN did not change after move: still {new_qn}"
        )

        parent_prefix, nano = _extract_sub_nano(new_qn)
        assert parent_prefix == domain_c_qn, (
            f"Sub2 parent prefix after move: expected {domain_c_qn}, "
            f"got {parent_prefix} (full QN: {new_qn})"
        )

        attrs = _read_entity_attrs(client, sub2_guid)
        parent_domain_qn = attrs.get("parentDomainQualifiedName")
        assert parent_domain_qn == domain_c_qn, (
            f"Sub2 parentDomainQualifiedName: expected {domain_c_qn}, "
            f"got {parent_domain_qn}"
        )

        ctx.set("move_sub2_nano", nano)
        ctx.set("move_sub2_qn", new_qn)
        print(f"  [domain-move] Sub2 after move to C: {new_qn}")

    @test("verify_prod_sub2_cascade", tags=["move", "data_mesh", "cross_domain"], order=37,
          depends_on=["verify_sub2_under_c"])
    def test_verify_prod_sub2_cascade(self, client, ctx):
        """Verify ProdSub2 QN cascaded: {new_sub2_qn}/product/{prod_nano}."""
        new_sub2_qn = ctx.get("move_sub2_qn")
        old_prod_qn = ctx.get("move_prod_sub2_qn")

        prod_guid = ctx.get_entity_guid("move_prod_sub2")
        prod_qn = _wait_for_qn_change(client, prod_guid, old_prod_qn, max_wait=30)
        assert prod_qn, (
            f"Expected qualifiedName on ProdSub2 after cascade ({prod_guid})"
        )

        prod_prefix, prod_nano = _extract_product_nano(prod_qn)
        assert prod_prefix == new_sub2_qn, (
            f"ProdSub2 parent prefix not cascaded: expected {new_sub2_qn}, "
            f"got {prod_prefix} (full QN: {prod_qn})"
        )
        ctx.set("move_prod_sub2_nano", prod_nano)
        ctx.set("move_prod_sub2_qn", prod_qn)
        print(f"  [domain-move] ProdSub2 after cascade: {prod_qn}")

    # ================================================================
    # MOVE 6: Deep cross-move — SubSub from Sub(B) to directly under C
    # ================================================================

    @test("move_subsub_to_c", tags=["move", "data_mesh", "cross_domain"], order=40,
          depends_on=["verify_cascade_after_move_to_b", "create_super_domain_c"])
    def test_move_subsub_to_c(self, client, ctx):
        """MOVE: Move SubSub from under Sub (which is under B) to directly under C.

        Tests moving a deeply nested subdomain to a different branch.
        SubSub goes from 3 levels deep (B->Sub->SubSub) to 2 levels (C->SubSub).
        """
        subsub_guid = ctx.get_entity_guid("move_subsub")
        subsub_qn = ctx.get("move_subsub_qn")
        domain_c_guid = ctx.get_entity_guid("move_domain_c")
        assert subsub_guid and subsub_qn and domain_c_guid, (
            "Required entities not created"
        )

        resp = client.post("/entity", json_data={
            "entity": {
                "typeName": "DataDomain",
                "guid": subsub_guid,
                "attributes": {
                    "qualifiedName": subsub_qn,
                    "name": self.subsub_name,
                },
                "relationshipAttributes": {
                    "parentDomain": {
                        "guid": domain_c_guid,
                        "typeName": "DataDomain",
                    },
                },
            }
        }, timeout=60)
        assert_status_in(resp, [200, 400, 403])
        if resp.status_code != 200:
            raise SkipTestError(
                f"Move SubSub to C returned {resp.status_code}"
            )
        print(f"  [domain-move] Move SubSub to C: {resp.status_code}")

    @test("verify_subsub_under_c", tags=["move", "data_mesh", "cross_domain"], order=41,
          depends_on=["move_subsub_to_c"])
    def test_verify_subsub_under_c(self, client, ctx):
        """Verify SubSub QN now has domain C as parent prefix."""
        subsub_guid = ctx.get_entity_guid("move_subsub")
        old_qn = ctx.get("move_subsub_qn")
        domain_c_qn = ctx.get("move_domain_c_qn")

        new_qn = _wait_for_qn_change(client, subsub_guid, old_qn, max_wait=30)
        assert new_qn and new_qn != old_qn, (
            f"SubSub QN did not change after move: still {new_qn}"
        )

        parent_prefix, nano = _extract_sub_nano(new_qn)
        assert parent_prefix == domain_c_qn, (
            f"SubSub parent prefix after move: expected {domain_c_qn}, "
            f"got {parent_prefix} (full QN: {new_qn})"
        )

        attrs = _read_entity_attrs(client, subsub_guid)
        parent_domain_qn = attrs.get("parentDomainQualifiedName")
        assert parent_domain_qn == domain_c_qn, (
            f"SubSub parentDomainQualifiedName: expected {domain_c_qn}, "
            f"got {parent_domain_qn}"
        )

        ctx.set("move_subsub_nano", nano)
        ctx.set("move_subsub_qn", new_qn)
        print(f"  [domain-move] SubSub after move to C: {new_qn}")

    # ================================================================
    # MOVE 7: Move product from super domain to subdomain
    # ================================================================

    @test("create_second_product_under_a", tags=["move", "data_mesh", "crud"], order=42,
          depends_on=["create_super_domain_a"])
    def test_create_second_product_under_a(self, client, ctx):
        """Create a second product under domain A for product-to-subdomain move."""
        domain_guid = ctx.get_entity_guid("move_domain_a")
        entity = build_data_product_entity(name=self.prod_a2_name,
                                           domain_guid=domain_guid)
        guid, _ = _create_entity(client, entity, "ProductA2")
        ctx.register_entity("move_prod_a2", guid, "DataProduct")
        ctx.register_entity_cleanup(guid)

        qn = _read_entity_qn(client, guid)
        assert qn, f"Expected qualifiedName on prod-a2 ({guid})"
        ctx.set("move_prod_a2_qn", qn)

        parent_prefix, nano = _extract_product_nano(qn)
        domain_a_qn = ctx.get("move_domain_a_qn")
        assert parent_prefix == domain_a_qn, (
            f"ProdA2 parent prefix mismatch: expected {domain_a_qn}, "
            f"got {parent_prefix} (full QN: {qn})"
        )
        ctx.set("move_prod_a2_nano", nano)
        print(f"  [domain-move] ProdA2: guid={guid}, qn={qn}")

    @test("move_product_super_to_sub", tags=["move", "data_mesh"], order=45,
          depends_on=["create_second_product_under_a", "verify_sub2_under_c"])
    def test_move_product_super_to_sub(self, client, ctx):
        """MOVE: Move ProdA2 from super domain A to subdomain Sub2 (now under C).

        Tests product move from a super domain to a subdomain.
        """
        import json

        prod_guid = ctx.get_entity_guid("move_prod_a2")
        current_qn = ctx.get("move_prod_a2_qn")
        sub2_guid = ctx.get_entity_guid("move_sub2")
        sub2_qn = ctx.get("move_sub2_qn")
        assert prod_guid and current_qn and sub2_guid, "Required entities not created"

        assets_dsl = json.dumps({
            "query": {"bool": {"must": [
                {"term": {"__guid": "00000000-0000-0000-0000-000000000000"}},
            ]}}
        })

        resp = client.post("/entity", json_data={
            "entity": {
                "typeName": "DataProduct",
                "guid": prod_guid,
                "attributes": {
                    "qualifiedName": current_qn,
                    "name": self.prod_a2_name,
                    "dataProductAssetsDSL": assets_dsl,
                },
                "relationshipAttributes": {
                    "dataDomain": {
                        "guid": sub2_guid,
                        "typeName": "DataDomain",
                    },
                },
            }
        }, timeout=60)
        assert_status_in(resp, [200, 400, 403])
        if resp.status_code != 200:
            raise SkipTestError(
                f"Move ProdA2 to Sub2 returned {resp.status_code}"
            )

        # Poll for QN change
        new_qn = _wait_for_qn_change(client, prod_guid, current_qn, max_wait=30)
        assert new_qn, f"Expected qualifiedName on ProdA2 after move ({prod_guid})"

        prod_prefix, prod_nano = _extract_product_nano(new_qn)
        assert prod_prefix == sub2_qn, (
            f"ProdA2 parent prefix after move: expected {sub2_qn}, "
            f"got {prod_prefix} (full QN: {new_qn})"
        )
        ctx.set("move_prod_a2_nano", prod_nano)
        ctx.set("move_prod_a2_qn", new_qn)
        print(f"  [domain-move] ProdA2 after move to Sub2: {new_qn}")

    # ================================================================
    # CLEANUP (delete in reverse: products, sub-sub, sub, domains)
    # ================================================================

    @test("delete_move_hierarchy", tags=["move", "data_mesh", "crud"], order=80)
    def test_delete_move_hierarchy(self, client, ctx):
        """Delete all entities created by this suite in reverse order."""
        for name in ("move_prod_a2", "move_prod_sub2", "move_prod_sub", "move_prod_a",
                     "move_subsub", "move_sub2", "move_sub",
                     "move_domain_c", "move_domain_b", "move_domain_a"):
            guid = ctx.get_entity_guid(name)
            if guid:
                resp = client.delete(f"/entity/guid/{guid}")
                assert_status_in(resp, [200, 204, 404])
                print(f"  [domain-move] Deleted {name}: {resp.status_code}")
