name: GitHub-Jira Link Action
run-name: ${{ github.actor }} is ensuring Jira ID is present in PR title
on:
  pull_request:
    types: [opened, edited, synchronize, reopened]
    branches: [main, staging, master, beta, develop, prod, development]

jobs:
  Enforce-GitHub-Jira-Link-Action:
    runs-on: ubuntu-latest
    if: ${{ !contains(fromJson('["main", "staging", "master", "beta", "develop", "prod", "development"]'), github.event.pull_request.head.ref) }}
    steps:
      - name: Enforce Pull Request Title includes Jira Issue Key
        uses: ryanvade/enforce-pr-title-style-action@v2.1.1